[server]
enableXsrfProtection = false
enableCORS = false
maxUploadSize=5120
port = 8502
[theme]
primaryColor="#D9895B"
backgroundColor="#161616"
secondaryBackgroundColor="#353535"
textColor="#FAFAFA"
font="sans serif"