[server]
port = 8501
address = "0.0.0.0"
enableXsrfProtection = false
enableCORS = false
maxUploadSize = 5120

[theme]
base = "dark"
primaryColor = "#D9895B"
backgroundColor = "#161616"
secondaryBackgroundColor = "#353535"
textColor = "#FAFAFA"
font = "sans serif"
